### ISSUE TITLE
Categories are not showing up with sql_mode

### ISSUE THREAD

**Issue by mrsamse** [CONTENIDO/CONTENIDO#124]
I created a local website on my MAMP with Contenido 4.10.1 and everything worked fine. Now I uploaded the website to the real sever. Unfortunately the categories are not showing up, when I want to edit an article under Content -> Article and I get this error in the log:

> Database failure: 3065 (Expression #2 of ORDER BY clause is not in SELECT list, references column 'balp_db1.c.idtree' which is not in SELECT list; this is incompatible with DISTINCT) - /contenido/main.php?area=con&frame=2&contenido=6cm6gitt4uqgf6hjmuk6c4lfja SELECT DISTINCT a.idcat, a.parentid, a.preid, a.postid, a.parentid, b.name, b.idlang, b.visible, b.public, c.level, d.idtpl FROM con_cat AS a LEFT JOIN con_cat_lang AS b ON a.idcat = b.idcat LEFT JOIN con_cat_tree AS c ON (a.idcat = c.idcat AND b.idcat = c.idcat) LEFT JOIN con_template_conf AS d ON b.idtplcfg = d.idtplcfg WHERE    a.idclient = 1 ORDER BY b.idlang DESC, c.idtree ASC 
" at reportHalt() [class.db.driver.handler.php(1013)]
	reportHalt() called in file class.db.driver.handler.php(985)
	halt() called in file class.db.driver.handler.php(705)
	query() called in file include.con_str_overview.php(584)
	include_once() called in file main.php(202)

The main difference from my local machine and the server is the sql mode. On my local machine I have no sql mode set but on the server it is set like this:

>ONLY_FULL_GROUP_BY,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION

Unfortunately I can't change the sql mode on this server.

Anyone got a solution to this?

**Comment by muratpurc** [comment]
@mrsamse:

The following change should fix the issue:

1. Open file "contenido/includes/include.con_str_overview.php"
2. Add "c.idtree, " between the list of columns (line 566 - 577)

A full example of the statement:
```
$sql = "SELECT DISTINCT " .
        "a.idcat, " .
        "a.parentid, " .
        "a.preid, " .
        "a.postid, " .
        "a.parentid, " .
        "b.name, " .
        "b.idlang, " .
        "b.visible, " .
        "b.public, " .
        "c.level, " .
        "c.idtree, " .
        "d.idtpl " .
        "FROM {$cfg['tab']['cat']} AS a " .
        "LEFT JOIN {$cfg['tab']['cat_lang']} AS b ON a.idcat = b.idcat " .
        "LEFT JOIN {$cfg['tab']['cat_tree']} AS c ON (a.idcat = c.idcat AND b.idcat = c.idcat) " .
        "LEFT JOIN {$cfg["tab"]["tpl_conf"]} AS d ON b.idtplcfg = d.idtplcfg " .
        "WHERE " .
        "   a.idclient = {$client} " .
        "ORDER BY b.idlang {$sOrder}, c.idtree ASC ";
```

But I recommend you to set the SQL-Mode on the server, you can find an example for how to do it in the CONTENIDO forum:
https://forum.contenido.org/viewtopic.php?f=115&t=43780

Your provider should allow you to modify the SQL mode, at least for your session. If not, then you won't be able to run CONTENIDO on this server since CONTENIDO is not compatible with some stricter SQL-mode settings.
