### ISSUE TITLE
PHP 8 Support

### ISSUE THREAD

**Issue by kw-pr** [CONTENIDO/CONTENIDO#236]
As there is no support for PHP 8 at the moment I open up a ticket for this.
For me this should be the overall main priority at the moment.

PHP 8.1 is about to be released soon. Active support for PHP 7.4 ends [this month](https://www.php.net/supported-versions.php). Security support in only a year and we also need time to migrate pages to PHP 8 after Contenido is ready.

In the [forum](https://forum.contenido.org/viewtopic.php?f=78&t=44567) I am counting 11 people mentioning this issue.

**Comment by gonatan** [comment]
Migration guide: https://www.php.net/manual/en/migration80.php

**Comment by kw-pr** [comment]
This can be automated using [rector](https://github.com/rectorphp/rector) with [php80](https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#php80) set.

**Comment by muratpurc** [comment]
As far as I understood, using Rector with the php80 set would modify the code by injecting new PHP 8 features in it, like replacing switch() against match() or using class constructor property promotion.

We don't want to raise the PHP requirements to 8.0, we should adapt the code to be compatible with PHP 8.0.

By the way, what kind of issues do we have with PHP 8.0? I'm asking this, because I don't remember having seen an error while running the current development branch on a PHP 8.0 environment.

A code inspection against PHP 8 returns a lot of warnings and some errors but none of them seem to be critical in terms of running CONTENIDO under PHP 8.

My biggest concern is the backward incompatible change in [string to number comparsion](https://www.php.net/manual/en/migration80.incompatible.php#migration80.incompatible.core.string-number-comparision).

Newer code in CONTENIDO uses strict comparsion in most cases, but we have a lot of legacy code with lax comparsions. Those cases must be analyzed/changed manually and individually, no software can guess what the intension of the author was..

**Comment by kw-pr** [comment]
Yes, sorry about this. I meant [phpstan](https://github.com/phpstan/phpstan) or [PHPCompatibility](https://github.com/PHPCompatibility/PHPCompatibility) can help finding issues.

**Comment by kw-pr** [comment]
Regarding the string to number comparison I found a [rule for phpstan](https://gist.github.com/b1rdex/d32a9a6b55849fec5ded7a5eb5cc6a24). Might be helpful.

**Comment by muratpurc** [comment]
Can someone test this branch and give me feedback please?

**Comment by Faar400** [comment]
I have a running Contenido now with php 8.0.x and it works with some issues.
One of them is this:
PHP Fatal error:  Uncaught ValueError: str_repeat(): Argument #2 ($times) must be greater than or equal to 0 in /home/contenido/includes/functions.general.php:1186

As much as i remember, it's the same like this issue: 
https://github.com/CONTENIDO/CONTENIDO/issues/245
@purcaholic

**Comment by kw-pr** [comment]
Looks like `$props["level"]` can be [empty](https://github.com/CONTENIDO/CONTENIDO/blob/develop/contenido/includes/functions.general.php#L1162):

    str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", $props["level"] - 1);

See [functions.general.php:1186](https://github.com/CONTENIDO/CONTENIDO/blob/develop/contenido/includes/functions.general.php#L1186)

This might be a fix:

    str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", max(0, $props["level"] - 1));

**Comment by Faar400** [comment]
It could work, even if $props["level"] is character instead of numeric, because character in max() will be changed to 0.
It seems similar to 'if($props["level"] < 1)$props["level"] = 1;' but much shorter.
One has to test it.

My solution works already, thats why i have no test enviroment.

**Comment by muratpurc** [comment]
> As much as i remember, it's the same like this issue:

Yes, it is the same issue as I mentioned in the PR https://github.com/CONTENIDO/CONTENIDO/pull/246#issuecomment-1113288685
