### ISSUE TITLE
ModRewrite Plugin: unnessary check throws logfile error

### ISSUE THREAD

**Issue by tone2tone** [CONTENIDO/CONTENIDO#273]
/contenido/plugins/mod_rewrite/classes/class.modrewriteurlstack.php
at line 200 
states in its original code:
`if (!isset($aUrl['params']) && !is_array($aUrl['params'])) {`

The second check is redundant and throws an error with PHP8. If $aUrl is not existing as per first check, then you can't check it on its array-or-non-array-state.
New code should read:
`if (!isset($aUrl['params'])) {`

**Comment by Faar400** [comment]
It's funny, because it's true.
In file /contenido/plugins/mod_rewrite/includes/config.plugins.php at line 128 even isn't a check with isset().
`if ((int)$_GET['idart'] == 0 && (int)$_GET['idcat'] == 0 && (int)$_POST['idart'] == 0 && (int)$_POST['idcat'] == 0) {`

And there are a lot of such things in a lot of plugins.

**Comment by Faar400** [comment]
In mr config.plugins.php are four variables in question.
It's annoying to aks everytime `if(isset($_GET...))` and so on.
Maybe, there is better way if we use `if ( $_SERVER['REQUEST_METHOD'] == 'POST' ) {} ELSE {}` ?

**Comment by kw-pr** [comment]
@tone2tone True. You could make a PR for this. 

But I am not sure if anyone here is still merging. @purcaholic Maybe?

@Faar400 

With `$_SERVER['REQUEST_METHOD'] === 'POST'` we still don't know about what variables exists. I don't think that would help.

There is also the null coalescing operator `$_GET['idart'] ?? 0`, `empty($_GET['idart'])` or you could also make a helper function. Depending on the case.

**Comment by Faar400** [comment]
@purcaholic is still merging, if he finds time. Today he was seen in the forum.

There are a lot of such issues in different files.
For example in file /contenido/includes/include.logs.php on line 86 it is _Trying to access array offset on value of type null_
You can check if isset($value["name"]) but this won't solve the problem because the code below assumes that there is a value in $value["name"].
So what to do if $value["name"] has no value?
Why it was null?

**Comment by kw-pr** [comment]
I was just wondering because there was no merge for half a year. If I would come along I would assume this project is dead.

But back to topic. You mean [this](https://github.com/CONTENIDO/CONTENIDO/blob/develop/contenido/includes/include.logs.php#L86)
I would wrap the whoe block in `if (isset($value["name"]))`

```
foreach ($actions as $key => $value) {
  if (isset($value["name"])) {
    $selected = (strcmp($idqaction, $key) == 0) ? ' selected="selected"' : '';

    // $areaname = $classarea->getAreaName($actionColl->getAreaForAction($value["name"]));
    $areaname = $value["areaname"];
    $actionDescription = $lngAct[$areaname][$value["name"]];

    if ($actionDescription == "") {
        $actionDescription = $value["name"];
    }

    $actionSelect .= '<option value="' . $key . '"' . $selected . '>' . $value['name'] . ' (' . $actionDescription . ')</option>';
  }
}
```

If it is missing, no `$actionSelect` would be added. 

But I did not check the whole code, so not sure what am I doing here.

**Comment by muratpurc** [comment]
Hi @tone2tone 

> /contenido/plugins/mod_rewrite/classes/class.modrewriteurlstack.php at line 200 states in its original code: `if (!isset($aUrl['params']) && !is_array($aUrl['params'])) {`
> 
> The second check is redundant and throws an error with PHP8. If $aUrl is not existing as per first check, then you can't check it on its array-or-non-array-state. New code should read: `if (!isset($aUrl['params'])) {`

can you please explain how to reproduce this error?
I mean, we shouldn't just take over pull-requests without knowing the reason or the way to reproduce it.

I have following PHP environment and don't get such errors:
```
PHP Version: 8.0.0
error_reporting = E_ALL & ~(E_STRICT | E_NOTICE | E_WARNING) (30709)
```

**Addition:**
If you use `E_ALL` for the `error_reporting` setting, then you may get a lot of errors. CONTENIDO is not fully compatible with PHP 8 and its strict `error_reporting` setting. Please use the value from above to solve this issue.

**Comment by muratpurc** [comment]
Hi @Faar400 ,

> In file /contenido/plugins/mod_rewrite/includes/config.plugins.php at line 128 even isn't a check with isset().
> if ((int)$_GET['idart'] == 0 && (int)$_GET['idcat'] == 0 && (int)$_POST['idart'] == 0 && (int)$_POST['idcat'] == 0) {

This part of the code needs to be refactored, it was working in the past but not in newer PHP versions since it gets stricter.
Yes, we need here at least a `isset(...)` or a  `empty(...)` check before accessing the array keys.

> In mr config.plugins.php are four variables in question. It's annoying to aks everytime `if(isset($_GET...))` and so on. Maybe, there is better way if we use `if ( $_SERVER['REQUEST_METHOD'] == 'POST' ) {} ELSE {}` ?

The method could be POST and the parameter could still be passed via GET, therefore the idea to check for the request method seems not to be helpful.

**Comment by muratpurc** [comment]
Hi @Faar400 ,

> There are a lot of such issues in different files. For example in file /contenido/includes/include.logs.php on line 86 it is _Trying to access array offset on value of type null_ You can check if isset($value["name"]) but this won't solve the problem because the code below assumes that there is a value in $value["name"]. So what to do if $value["name"] has no value? Why it was null?

Same question to you, what version of PHP do you use an what is your error_reporting setting.
There are a lot of people, running the corrent development version of CONTENIDO with PHP 8 and they don't have any issues with it.

**Comment by muratpurc** [comment]
PHP 8 with the default `error_reporting` setting, which is `E_ALL`, results in following errors in ModRewrite plugin:

```
Warning: Undefined array key "idart" in .../contenido/plugins/mod_rewrite/includes/config.plugin.php on line 128
Warning: Undefined array key "idcat" in .../contenido/plugins/mod_rewrite/includes/config.plugin.php on line 128
Warning: Undefined array key "idart" in .../contenido/plugins/mod_rewrite/includes/config.plugin.php on line 128
Warning: Undefined array key "idcat" in .../contenido/plugins/mod_rewrite/includes/config.plugin.php on line 128
Warning: Undefined array key "params" in .../contenido/plugins/mod_rewrite/classes/class.modrewriteurlstack.php on line 200
```

One solution is to create a file `data/config/<environment>/config.local.php`, if it doesn't exists, and define the error_reporting setting as follows:

`$cfg['php_error_reporting'] = E_ALL & ~(E_STRICT | E_NOTICE | E_WARNING);`

Other solution is to fix the code in the ModRewrite plugin, but I'm afraid that if we run PHP in strict error_reporting setting, we'll face many other issues.

**Comment by Faar400** [comment]
Hi @purcaholic 
it is PHP 8.0.20 and i didn't change Error reporting and as i remember, i didn't have this errors shown months before.
Maybe the server settings have changed?
The page is running except frontend users.

As much as i understood @tone2tone is, that his code was "doppeltgemoppelt" and if you check for isset an array, you don't need to check second time if this array is an array. But it throws PHP 8 Error, because if it is not set, it can't be an array anyway.
There are a lot of these little misconceptions that PHP 8 now flags up.
But CONTENIDO runs anyway, except frontenduser-permissions. Maybe this is another bug.

**Comment by Faar400** [comment]
> Other solution is to fix the code in the ModRewrite plugin

@purcaholic As much as i understood the ModRewrite code at this part, there is no idart and idcat in this moment (clicking in backend), but the code is expecting and be checked for idart and idcat. That's why the errors occour.
To avoid the error messages, it should be used isset(), empty() or count().
I'm sure, if i am in Frontend, there will be idart and idcat.

Once you was thinking the same way and you checked in line 125 of config.plugin.php for Backend use:
`if (!isset($contenido)) {
        // we are not in backend, add cec functions for rewriting`
But it seems it does not work anymore?
I havent been in Frontend, only i was in Backend.
Maybe, $contenido issn't set there?

**Comment by muratpurc** [comment]
> As much as i understood @tone2tone is, that his code was "doppeltgemoppelt" and if you check for isset an array, you don't need to check second time if this array is an array. But it throws PHP 8 Error, because if it is not set, it can't be an array anyway. There are a lot of these little misconceptions that PHP 8 now flags up. But CONTENIDO runs anyway, except frontenduser-permissions. Maybe this is another bug.

@Faar400  the `$aUrl['params']` ist set two lines above and only within the `if (isset($aUrl['query'])) {` condition.

Therefore we need to check, if `$aUrl['params']` exists and if it is an array. The check is not unnecessary, we must ensure to return an array with the key `params` where the value is also an array.

**Comment by kw-pr** [comment]
@purcaholic I think he is right. The check is not needed.
I tried it here: https://onlinephp.io/c/c60ca

**Comment by muratpurc** [comment]
> > Other solution is to fix the code in the ModRewrite plugin
> 
> @purcaholic As much as i understood the ModRewrite code at this part, there is no idart and idcat in this moment (clicking in backend), but the code is expecting and be checked for idart and idcat. That's why the errors occour. To avoid the error messages, it should be used isset(), empty() or count(). I'm sure, if i am in Frontend, there will be idart and idcat.
> 
> Once you was thinking the same way and you checked in line 125 of config.plugin.php for Backend use: `if (!isset($contenido)) { // we are not in backend, add cec functions for rewriting` But it seems it does not work anymore? I havent been in Frontend, only i was in Backend. Maybe, $contenido issn't set there?

The ModRewrite plugin is not active in the backend, the check for `idart` and `idcat` is, as far as I remember, the logic from earlier times. The resolving of the seo url and setting the proper variables will be skipped, if the request contains the `idart` or `idcat` parameter.

**Comment by muratpurc** [comment]
> @purcaholic I think he is right. The check is not needed. I tried it here: https://onlinephp.io/c/c60ca

@kw-pr  the `$aUrl['params']` is set by calling `parse_str($aUrl['query'], $aUrl['params']);``, and the second parameter of the function `$aUrl['params']` will always be set as an array. You are right, the check is not neccessary.

The code before was wrong, now it is working, but with a not needed `is_array()` check. 
We can leave it as it is or we can fix it.
