### ISSUE TITLE
Smiley breaks Tinymce

### ISSUE THREAD

**Issue by AndrasDF** [CONTENIDO/CONTENIDO#380]
Entering 😊 in WYSIWYG Editor or `&#128522;` in Source-Editor of the WYSIWYG Editor removes everything after the emoticon and the emoticon itself when saved.

**Comment by muratpurc** [comment]
The connection to the database is most likely made by using `utf8`, and you need to change this to `utf8mb4` in order to be able to store and retrieve content having unicode, e.g. smileys.

Open your `config.php` in `{installation_path}/data/config/{emvironment}/` and set the database connection setting for 'charset' to 'utf8mb4'. This should solve your issue.

**Comment by Faar400** [comment]
When I set up a website in Thai, I also had to convert all table columns with readable characters to UTF8-xxx too, otherwise the Thai characters were saved incorrectly.

**Comment by muratpurc** [comment]
CONTENIDOs' default charset for database connections is `utf8`. If you want to use emojis, Asian symbols, mathematical symbols, etc., then you have to change this manually to multi-byte UTF-8 (`utf8mb4`) after the installation.

We can think about changing the default charset to `utf8mb4` and the collation to `utf8mb4_unicode_ci` in the CONTENIDO setup, so that future installations won't have such issues.

**Comment by Faar400** [comment]
Yes, it would be real multilanguage able.

**Comment by muratpurc** [comment]
The creation of MySQL tables with the charset `utf8mb4` on new CONTENIDO installations ist implemented. See pull request #404.
