### ISSUE TITLE
Teaser-Modul - DB Overload if you have many Categories

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#40]
If you have much categories in Contenido, the Teaser-Module has a bottleneck in requesting those Categories and each of the concatenated Articles for "BackendView".

The Teaser-Module loads those Categories and Articles for the Popup-Dialoge

![Auswahl_332](https://user-images.githubusercontent.com/4060949/69437440-9b700080-0d43-11ea-8643-5063719ea4ba.png)

So if you have 5 Teaser at your Page, the Backend will load the function "buildCategorySelect" 10 times and have a huge overload (14509 DB-Requests if con_cat_art has 763 entries and con_cat 210 entries) of DB-Requests to preload those Categories & Articles for "EACH" of the Teasers

![Auswahl_305](https://user-images.githubusercontent.com/4060949/69437454-a165e180-0d43-11ea-8145-bef9124aacce.png)

https://forum.contenido.org/viewtopic.php?f=98&t=39028

After those first 14500 request, another 14500 request are started for the "advanced-Tabs" of the Teaser Dialog

**Comment by tone2tone** [comment]
@purcaholic Okay.. this one I experienced myself in a website with LOTS of categories and articles and up to 5 article lists too... On the other hand this is a very rare usecase. Avoiding to much load on multiple buildCategorySelect is tricky, when it comes to avoid if on a global level. 
What we could do though is to avoid multiple build up WITHIN one teaser list. I have a suggestion at hand but will only submit if you think that's a good idea.
class.content.type.teaser.php could hold a new function:

```
    /**
     * Returns the category list in select form as source code string.
     *
     * @param string to set the default option value
     * @return string
     */
    private function _catListHelper($catDefault)
    {
        
		$catDefault = intval($catDefault);
		if ($this->_catList == '') {
			$this->_catList = buildCategorySelect('teaser_category_' . $this->_id, 0, 0);
		}
		
		$returnString = ($catDefault > 0) ? str_replace('value="' .$catDefault . '"', 'value="' .$catDefault . '" selected="selected"', $this->_catList) : $this->_catList;
		
        return $returnString;
    }
```

It kinda outsources the category build up and comes up with a new variable to hold its content through all class functions. This new function adds a default value AFTER category build up instead of applying it straight away, so that $this->_catList always holds the clean category list without presets. This way we can check if the list has been produced before, and only if not it will be produced once throughout one teaser module.
This would only require a few changes additions, e.g.
```
    /**
     * Variable for category list source code string.
     *
     * @var int
     */
    private $_catList = '';	
```
and replacing the old calls for buildCategorySelect in two functions:
`$wrapperContent[] = $this->_catListHelper($this->_settings['teaser_category']);`
`$wrapperContent[] = $this->_catListHelper(0);`

Shall I submit a corresponding commit?

**Comment by dceonline** [comment]
Hi,

what about using a static variable to hold results from first category-select in teaser class?
One can also change behaviour of function buildCategorySelect, so this function uses a cache to remember selects.

**Comment by tone2tone** [comment]
Good idea! Will come up with a pull request and minimal changes. Would like to keep buildCategorySelect untouched to avoid unwanted behaviour elsewhere for the time being.
