### ISSUE TITLE
[Bug] include.con_content_list.php: Rohdaten-Tab shows nothing but imgEditors

### ISSUE THREAD

**Issue by tone2tone** [CONTENIDO/CONTENIDO#401]
Around line 1082, the if clause ends with
`$code = str_ireplace($search, $replacements, $layoutCode);`
The following two lines have to be included into this clause as well, otherwise the Rohdaten-Tab will not allow to edit or delete html, htmlhead and such. 

The if-clause has to finish with:
```
        $code = str_ireplace($search, $replacements, $layoutCode);
		// execute CEC hook
		$layoutCode = cApiCecHook::executeAndReturn('Contenido.Content.conGenerateCode', $code);
    }
```

**Comment by muratpurc** [comment]
Hi @tone2tone ,

thank you for the bug report.

The bug is fixed, but in a different way than what you suggested. The chain `Contenido.Content.conGenerateCode` is intended to be executed only once per code generation, so it was solved differently.

Please see the changes in pull request https://github.com/CONTENIDO/CONTENIDO/pull/402 .

**Comment by tone2tone** [comment]
Thanks! Applied the changes locally and your solution works perfectly fine. You can execute the pull request IMHO.
