### ISSUE TITLE
Templates: Module configuration gets lost after layout change

### ISSUE THREAD

**Issue by gonatan** [CONTENIDO/CONTENIDO#48]
**Problem**
When changing the layout of a template, modules are no more related to their container.
This is due to a change in CON-2546 where all module relations are removed.
See http://forum.contenido.org/viewtopic.php?f=98&t=37138 for the discussion about this issue.

**Requirements**
When changing the layout of a template, module relations should only be deleted if:
- the container is not available anymore
- the module does not fullfill the container constraints (e.g. if the container is "fixed")

**Comment by tone2tone** [comment]
The forum hotfix is really just a hotfix. I tried to understand a bit better how functions.tpl.php works when a template is edited or its layout base is changed (which is the same usecase).
- the function reads each module assigned to a container in this template as per con_container and stores it in an array, meaning: that's obviously the container numbers from the OLD configuration plus the changes made on specific containers.
- when changing a layout for a template, all entries for this template in con_container are erased as a final step in 4.10.x.
- When trying to avoid that the easy way and saving the entries in con_containers as in normal editing mode, the values are built up from scratch again, BUT based on the stored array. It still holds container numbers from the old template and saves it too (let's call them old-old-values). This produces unnecessary database content.
- when changing layout once again, the new "on hold array" is now based on the (perhaps reduced) container availability and/or changed numbers, and as all old entries are deleted, the old-old-values are now not reproduced anymore.
- Taking this into consideration, it will not be possible to change a layout and back again and then show entries for a container that didn't exist in the "middle" layout as the values that are stored to database ALWAYS rely on the last available containers only not on what is stored in total in the database.

In order to keep at least some modules working when changing a template's layout, the approach has to be different.
It doesn't matter whether a template is just saved or changed. At all times, the template configuration has to be done from scratch. 
- New: the function now additionally reads which container numbers are REALLY available for the desired or assigned layout.
- After deletion of all entries, new entries are created. The "story array" is stepped through, container by container. The value is only stored if it is not 0 and if the container ID (coming from the last configuration) exists in the assigned layout as well. 
- This way, no junk is safed to database.

Will create a pull request soon.
